# Generated by Django 2.0.5 on 2019-02-12 08:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Experiences', '0001_initial'),
        ('Capabilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('description_en', tinymce.models.HTMLField(null=True, verbose_name='Description')),
                ('description_es', tinymce.models.HTMLField(null=True, verbose_name='Description')),
                ('picture', models.ImageField(upload_to='portfolio/', verbose_name='Picture')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='Date')),
                ('link', models.URLField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Experiences.Company', verbose_name='Company')),
                ('stack', models.ManyToManyField(to='Capabilities.Capability')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Project Type',
                'verbose_name_plural': 'Project Types',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.ProjectType', verbose_name='Project Type'),
        ),
    ]
