# Generated by Django 2.0.5 on 2019-02-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Site Name')),
                ('site_name_en', models.CharField(max_length=100, null=True, verbose_name='Site Name')),
                ('site_name_es', models.CharField(max_length=100, null=True, verbose_name='Site Name')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('in_development', models.BooleanField(default=False, verbose_name='In Development')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='CMS', verbose_name='Picture')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Phone')),
                ('welcome', models.TextField(blank=True, verbose_name='Welcome')),
                ('welcome_en', models.TextField(blank=True, null=True, verbose_name='Welcome')),
                ('welcome_es', models.TextField(blank=True, null=True, verbose_name='Welcome')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Job Title')),
                ('job_title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title')),
                ('job_title_es', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title')),
                ('contact', models.TextField(blank=True, verbose_name='Contact')),
                ('contact_en', models.TextField(blank=True, null=True, verbose_name='Contact')),
                ('contact_es', models.TextField(blank=True, null=True, verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'CMS',
            },
        ),
    ]
