# Generated by Django 2.0.5 on 2019-02-15 22:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='welcome',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Welcome'),
        ),
        migrations.AlterField(
            model_name='cms',
            name='welcome_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Welcome'),
        ),
        migrations.AlterField(
            model_name='cms',
            name='welcome_es',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Welcome'),
        ),
    ]
