# Generated by Django 2.0.5 on 2019-02-26 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Experiences', '0001_initial'),
        ('CMS', '0002_welcome_to_htmlfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cms',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='contact_en',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='contact_es',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='job_title_en',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='job_title_es',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='site_name_en',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='site_name_es',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='welcome',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='welcome_en',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='welcome_es',
        ),
        migrations.AddField(
            model_name='cms',
            name='cellphone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cellphone'),
        ),
        migrations.AddField(
            model_name='cms',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='cms',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='cms',
            name='current_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Experiences.Company', verbose_name='Current Work'),
        ),
        migrations.AddField(
            model_name='cms',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cms',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='cms',
            name='work_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='cms',
            name='work_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='cms',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cms',
            name='work_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='cms',
            name='work_state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='cms',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
