# Generated by Django 2.0.5 on 2019-02-12 08:31

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('link', models.URLField(blank=True)),
                ('color', colorfield.fields.ColorField(default='#6f42c1', max_length=18)),
                ('icon', models.FileField(upload_to='social', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
            },
        ),
    ]
